<?php
return [
    'Fantasy',
    'Historical Fiction',
    'Thriller',
    'Romance',
    'Science Fiction',
    'Mystery',
    'Poetry',
    'Drama',
    'Classics',
    'Comedy/Humor',
    'Religion/Spirituality',
    'Philosophy',
    'Psychology',
    'Business',
    'Young Adult',
    'Children Literature',
    'Memoir',
    'Autobiography',
    'Biography',
    'Self-Help',
    'Home & Garden',
    'Western',
    'Outdoors',
    'Fairy Tale',
    'Dystopian',
    'Travel',
    'Cookbooks',
    'Action',
    'Adventure',
    'Horror',
    'Military',
    'Sports',
    'History',
    'Popular Science',
    'Satire',
    'Art',
    'Health & Wellness',
    'Mythic Fiction',
    'Unidentified',
    'Fantasy & Adventure', 
    'Science Fiction & Fantasy', 
    'Historical Romance', 
    'Paranormal Romance', 
    'Crime & Mystery', 
    'Action & Adventure', 
    'Young Adult Fantasy',
    'Children\'s Fantasy', 
    'Historical Mystery', 
    'Graphic Novels & Comics',
    'Non-Fiction Biography', 
    'Self-Help & Personal Development', 
    'Contemporary Romance', 
    'Science & Technology', 
    'Travel & Adventure', 
    'Cookbooks & Food', 
    'Spirituality & Religion', 
    'True Crime & Mystery', 
    'Art & Photography', 
    'Personal Finance & Non-Fiction', 
];
?>
